[package]
name = "sfubuffer"
description = "sfu buffer library."
version = "0.0.4"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/rsfu"
license = "MIT"
readme = "README.md"
categories = ["multimedia", "multimedia::video", 'multimedia::audio']
keywords = ["webrtc", "video", "sfu"]
edition = "2018"

[dependencies]
bytesio = "0.1.27"
rtcp = "0.4.1"
rtp = "0.6.0"
sdp = "0.4.0"
webrtc = "0.2.0"
byteorder = "1.4.2"
thiserror = "1.0.25"
anyhow = "1.0.41"
tokio = "1.12.0"
bytes = "1.1.0"
webrtc-util =  "0.5.0"

