[package]
name = "sfubuffer"
description = "sfu buffer library."
version = "0.0.4"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/rsfu"
license = "MIT"
readme = "README.md"
categories = ["multimedia", "multimedia::video", 'multimedia::audio']
keywords = ["webrtc", "video", "sfu"]
edition = "2018"

[dependencies]
rtcp = "0.4.1"
rtp = "0.6.0"
